services:

  policydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - my_networks
    volumes:
      - policydata:/var/lib/mysql

networks:
  my_networks:

volumes:
  policydata: